// File generated by FlutterFire CLI
// Run `flutterfire configure` to update this file with your Firebase project config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEn4vJZrsGpVFgqSFsC66NkGughu4df_s',
    appId: '1:296631017185:web:a8918f319b477048f961a0',
    messagingSenderId: '296631017185',
    projectId: 'runforge-14e55',
    authDomain: 'runforge-14e55.firebaseapp.com',
    storageBucket: 'runforge-14e55.firebasestorage.app',
  );
}
